# Generated by Django 5.1.5 on 2025-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('TENANT_ADMIN', 'Tenant Admin'), ('SALES', 'Sales Team'), ('SUPPORT', 'Support Team'), ('SUPER_ADMIN', 'Super Admin')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(choices=[('BASIC', 'Basic Plan'), ('PRO', 'Pro Plan'), ('ELITE', 'Elite Plan')], default='BASIC', max_length=20),
        ),
    ]
