# Generated by Django 5.1.5 on 2025-08-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_tier',
            field=models.CharField(choices=[('PRO', 'Pro Plan'), ('ELITE', 'Elite Plan')], default='PRO', max_length=20),
        ),
    ]
