# Generated by Django 5.1.5 on 2025-08-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_migrate_basic_users_to_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', max_length=50),
        ),
    ]
