# Generated by Django 5.1.5 on 2025-08-30 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_currency_customuser_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Phone number must contain 9-20 digits and can include +, spaces, dashes, and parentheses.', regex='^\\+?[\\d\\s\\-\\(\\)]{9,20}$')]),
        ),
    ]
