# Generated by Django 5.1.5 on 2025-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("SUPER_ADMIN", "Super Admin")],
                default="USER",
                max_length=20,
            ),
        ),
    ]
