# Generated by Django 5.2.5 on 2025-08-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingorder',
            name='disclosed_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Iceberg order disclosed quantity'),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='instrument_type',
            field=models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURES', 'Futures'), ('OPTIONS', 'Options'), ('COMMODITY', 'Commodity'), ('CURRENCY', 'Currency')], default='EQUITY', help_text='Type of financial instrument', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='lot_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='option_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='position_type',
            field=models.CharField(choices=[('INTRADAY', 'Intraday'), ('DELIVERY', 'Delivery'), ('CARRY_FORWARD', 'Carry Forward')], default='INTRADAY', help_text='Position holding type', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='stoploss_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stop loss price for bracket orders', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target price for bracket orders', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='trailing_stoploss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trailing stop loss percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='underlying_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tradingorder',
            name='validity',
            field=models.CharField(default='DAY', help_text='Order validity (DAY, IOC, GTD)', max_length=10),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for F&O instruments', null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='instrument_type',
            field=models.CharField(choices=[('EQUITY', 'Equity'), ('FUTURES', 'Futures'), ('OPTIONS', 'Options'), ('COMMODITY', 'Commodity'), ('CURRENCY', 'Currency')], default='EQUITY', help_text='Type of financial instrument', max_length=20),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='lot_size',
            field=models.PositiveIntegerField(default=1, help_text='Lot size for F&O instruments'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='option_type',
            field=models.CharField(blank=True, choices=[('CALL', 'Call Option'), ('PUT', 'Put Option')], help_text='Call or Put for options', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Strike price for options', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='underlying_symbol',
            field=models.CharField(blank=True, help_text='Underlying asset for F&O (e.g., NIFTY for NIFTY24DEC19000CE)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tradingorder',
            name='order_type',
            field=models.CharField(choices=[('MARKET', 'Market Order'), ('LIMIT', 'Limit Order'), ('SL', 'Stop Loss'), ('SL_M', 'Stop Loss Market'), ('OCO', 'One Cancels Other'), ('BRACKET', 'Bracket Order'), ('COVER', 'Cover Order')], max_length=20),
        ),
        migrations.CreateModel(
            name='FuturesOptionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Full instrument symbol (e.g., NIFTY24DEC19000CE)', max_length=100, unique=True)),
                ('underlying_symbol', models.CharField(help_text='Underlying asset symbol', max_length=50)),
                ('instrument_type', models.CharField(choices=[('FUTURES', 'Futures'), ('OPTIONS', 'Options')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('option_type', models.CharField(blank=True, choices=[('CALL', 'Call Option'), ('PUT', 'Put Option')], max_length=10, null=True)),
                ('lot_size', models.PositiveIntegerField(default=1)),
                ('tick_size', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
                ('freeze_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity allowed in single order', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'F&O Instrument',
                'verbose_name_plural': 'F&O Instruments',
                'db_table': 'futures_options_data',
                'ordering': ['underlying_symbol', 'expiry_date', 'strike_price'],
                'indexes': [models.Index(fields=['underlying_symbol', 'expiry_date'], name='futures_opt_underly_bf0d4c_idx'), models.Index(fields=['symbol'], name='futures_opt_symbol_6c4558_idx'), models.Index(fields=['instrument_type', 'is_active'], name='futures_opt_instrum_08a86f_idx')],
            },
        ),
    ]
