# Generated by Django 5.1.5 on 2025-08-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_tradingorder_disclosed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='ai_justification',
            field=models.TextField(blank=True, help_text='Human-readable explanation of why this signal was generated'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='feature_importance',
            field=models.JSONField(default=dict, help_text='SHAP feature importance values explaining the signal'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='probability_explanation',
            field=models.JSONField(default=dict, help_text='Breakdown of factors contributing to confidence score'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='shap_values',
            field=models.JSONField(default=dict, help_text='SHAP values for each feature contributing to the decision'),
        ),
    ]
