# Generated by Django 5.1.5 on 2025-08-17 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_tradingstrategy_tradeapproval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('DAILY_SIGNALS', 'Daily Signal Generation'), ('MONTHLY_SIGNALS', 'Monthly Signal Generation'), ('DAILY_BACKTESTS', 'Daily Backtests'), ('MONTHLY_BACKTESTS', 'Monthly Backtests'), ('ACTIVE_STRATEGIES', 'Active Strategies'), ('API_CALLS_DAILY', 'Daily API Calls'), ('PORTFOLIO_POSITIONS', 'Portfolio Positions'), ('DATA_EXPORT_MONTHLY', 'Monthly Data Exports')], max_length=30)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
                ('last_daily_reset', models.DateField(auto_now_add=True)),
                ('last_monthly_reset', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Tracker',
                'verbose_name_plural': 'Usage Trackers',
                'db_table': 'trading_usage_tracker',
                'indexes': [models.Index(fields=['user', 'limit_type'], name='trading_usa_user_id_657f4b_idx'), models.Index(fields=['last_daily_reset'], name='trading_usa_last_da_606d4a_idx'), models.Index(fields=['last_monthly_reset'], name='trading_usa_last_mo_beadaa_idx')],
                'unique_together': {('user', 'limit_type')},
            },
        ),
    ]
