# Generated by Django 5.1.5 on 2025-10-01 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('plan_type', models.CharField(choices=[('FREE', 'Free Plan'), ('PRO', 'Pro Plan'), ('ELITE', 'Elite Plan')], max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('backtests_per_day', models.IntegerField()),
                ('live_strategies', models.IntegerField()),
                ('ai_model_studio_access', models.BooleanField(default=False)),
                ('marketplace_publishing', models.BooleanField(default=False)),
                ('institutional_models', models.BooleanField(default=False)),
                ('unlimited_backtests', models.BooleanField(default=False)),
                ('unlimited_strategies', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('custom_indicators', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of feature descriptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Payment'), ('TRIAL', 'Trial Period')], default='PENDING', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('backtests_used_today', models.IntegerField(default=0)),
                ('last_backtest_reset', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe'), ('BANK_TRANSFER', 'Bank Transfer'), ('FREE_TRIAL', 'Free Trial')], max_length=20)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('BACKTEST', 'Backtest'), ('LIVE_STRATEGY', 'Live Strategy'), ('MODEL_TRAINING', 'Model Training'), ('API_CALL', 'API Call'), ('MARKET_DATA', 'Market Data')], max_length=20)),
                ('usage_count', models.IntegerField(default=0)),
                ('usage_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_date', 'feature_type'],
                'unique_together': {('user', 'feature_type', 'usage_date')},
            },
        ),
    ]
