# Generated by Django 5.1.5 on 2025-08-17 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0002_fnostrategy_mlmodel_breakeven_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceEarnings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('LEASE_PAYMENT', 'Lease Payment'), ('COMMISSION', 'Platform Commission'), ('REFUND', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creator_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='ai_studio.modelleasing')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='ai_studio.mlmodel')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
