# Generated by Django 5.1.5 on 2025-08-17 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0003_marketplaceearnings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='modelreview',
            name='actual_performance',
        ),
        migrations.RemoveField(
            model_name='modelreview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='modelreview',
            name='title',
        ),
        migrations.RemoveField(
            model_name='modelreview',
            name='would_recommend',
        ),
        migrations.AddField(
            model_name='modelreview',
            name='actual_returns',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelreview',
            name='actual_win_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelreview',
            name='review_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelreview',
            name='verified_performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modelreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='modelreview',
            table=None,
        ),
    ]
