# Generated by Django 5.1.5 on 2025-08-17 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GMAIL', 'Gmail'), ('OUTLOOK', 'Outlook'), ('SENDGRID', 'SendGrid'), ('MAILGUN', 'Mailgun'), ('AWS_SES', 'Amazon SES'), ('CUSTOM', 'Custom SMTP')], default='GMAIL', help_text='Email service provider', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Enable email sending')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('email_address', models.EmailField(help_text='Email address to send from', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('email_password', models.TextField(help_text='Email password or app-specific password (encrypted)')),
                ('from_name', models.CharField(default='ShareWise AI', help_text='Display name for emails', max_length=100)),
                ('test_email', models.EmailField(blank=True, help_text='Email address for testing configuration', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ShareWise AI', help_text='Name of the platform', max_length=100)),
                ('site_url', models.URLField(default='http://localhost:3000', help_text='Frontend URL of the platform')),
                ('enable_user_registration', models.BooleanField(default=True, help_text='Allow new users to register')),
                ('require_email_verification', models.BooleanField(default=True, help_text='Require email verification for new users')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, default='The system is currently under maintenance. Please try again later.', help_text='Message to display during maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
    ]
