# Generated by Django 5.1.5 on 2025-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='api_key',
            field=models.TextField(blank=True, help_text='API Key for service providers (encrypted)', null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='auth_method',
            field=models.CharField(choices=[('PASSWORD', 'Username/Password'), ('OAUTH2', 'OAuth2'), ('API_KEY', 'API Key')], default='PASSWORD', help_text='Authentication method', max_length=20),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='oauth2_client_id',
            field=models.TextField(blank=True, help_text='OAuth2 Client ID', null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='oauth2_client_secret',
            field=models.TextField(blank=True, help_text='OAuth2 Client Secret (encrypted)', null=True),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='oauth2_refresh_token',
            field=models.TextField(blank=True, help_text='OAuth2 Refresh Token (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_password',
            field=models.TextField(blank=True, help_text='Email password or app-specific password (encrypted)', null=True),
        ),
    ]
